name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy both SE and NO workers
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Process uploaded content
        run: npm run process-uploaded

      - name: Build Astro site
        run: npm run build

      - name: Deploy Swedish worker (se.idag.ai)
        run: npm run deploy:se
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy Norwegian worker (no.idag.ai)
        run: npm run deploy:no
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deployment Summary
        run: |
          echo "✅ Successfully deployed both workers:"
          echo "🇸🇪 Swedish: se.idag.ai"
          echo "🇳🇴 Norwegian: no.idag.ai"